### ISSUE TITLE
Generate a token [Windows 11]

### ISSUE THREAD

**Issue by LucasB25** [idMJA/accessify#4]
```
PS C:\Users\LucasB25\Desktop\Spotify> npm start

> accessify@1.0.0 start
> tsup && node dist/server.js

CLI Building entry: src/server.ts, src/handler/browser.ts, src/handler/request.ts, src/handler/spotify.ts, src/types/spotify.ts, src/utils/logger.ts, src/utils/semaphore.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v8.5.0
CLI Using tsup config: C:\Users\LucasB25\Desktop\Spotify\tsup.config.ts
CLI Target: esnext
CLI Cleaning output folder
CJS Build start
CJS dist\server.js          12.60 KB
CJS dist\types\spotify.js   770.00 B
CJS dist\utils\semaphore.js 1.47 KB
CJS dist\utils\logger.js    1.86 KB
CJS dist\handler\request.js 2.95 KB
CJS dist\handler\browser.js 7.12 KB
CJS dist\handler\spotify.js 12.30 KB
CJS ⚡️ Build success in 21ms
[INFO] [Sat, 12 Jul 2025 14:01:29 GMT] Spotify Token API (Hono) listening on http://localhost:3000
[ERROR] [Sat, 12 Jul 2025 14:01:32 GMT] Error in getAccessToken page.goto: Target page, context or browser has been closed
Call log:
  - navigating to "https://open.spotify.com/", waiting until "load"

    at SpotifyBrowser.ensureBrowser (C:\Users\LucasB25\Desktop\Spotify\dist\server.js:85:22)
    at async SpotifyBrowser.fetchToken (C:\Users\LucasB25\Desktop\Spotify\dist\server.js:91:25)
    at async run (C:\Users\LucasB25\Desktop\Spotify\dist\server.js:323:25)
[WARN] [Sat, 12 Jul 2025 14:01:32 GMT] Failed to fetch initial Spotify token (attempt 1) page.goto: Target page, context or browser has been closed
Call log:
  - navigating to "https://open.spotify.com/", waiting until "load"

    at SpotifyBrowser.ensureBrowser (C:\Users\LucasB25\Desktop\Spotify\dist\server.js:85:22)
    at async SpotifyBrowser.fetchToken (C:\Users\LucasB25\Desktop\Spotify\dist\server.js:91:25)
    at async run (C:\Users\LucasB25\Desktop\Spotify\dist\server.js:323:25)
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

browserContext.newPage: Target page, context or browser has been closed
    at C:\Users\LucasB25\Desktop\Spotify\dist\server.js:94:36
    at C:\Users\LucasB25\Desktop\Spotify\dist\server.js:175:9
    at SpotifyBrowser.fetchToken (C:\Users\LucasB25\Desktop\Spotify\dist\server.js:92:12)
    at async run (C:\Users\LucasB25\Desktop\Spotify\dist\server.js:323:25)

Node.js v24.3.0
```

Unable to generate a token [Windows 11]

**Comment by idMJA** [comment]
is there a way to reproduce this error?

**Comment by LucasB25** [comment]
on my computer, yes. Afterwards, I don’t know. I tested with a simple classic use by following the tutorial

**Comment by LucasB25** [comment]
> on my computer, yes. Afterwards, I don’t know. I tested with a simple classic use by following the tutorial

if you need you can come test on my IDE

**Comment by idMJA** [comment]
> > on my computer, yes. Afterwards, I don’t know. I tested with a simple classic use by following the tutorial
> 
> if you need you can come test on my IDE

can I test it on your idea if you let me?

**Comment by idMJA** [comment]
or u can test this one
https://github.com/idMJA/accessify/pull/5

**Comment by EvilG-MC** [comment]
@LucasB25 try removing `--single-process` from the browser launch options argss

**Comment by idMJA** [comment]
fixed on https://github.com/idMJA/accessify/commit/ea9da8e8c0f177207d186b369076bf1f81c52454
thanks @EvilG-MC

**Comment by idMJA** [comment]
feel free to reopen this

**Comment by LucasB25** [comment]
> > > on my computer, yes. Afterwards, I don’t know. I tested with a simple classic use by following the tutorial
> > 
> > 
> > if you need you can come test on my IDE
> 
> can I test it on your idea if you let me?

I just tested, I no longer have an error but I still have the problem `Failed to retrieve secret from Spotify.`

that I no longer had the very first time I used this code

discord: lucasb25

**Comment by EvilG-MC** [comment]
> I just tested, I no longer have an error but I still have the problem `Failed to retrieve secret from Spotify.`
> 
> that I no longer had the very first time I used this code
> 
> discord: lucasb25

I think that's a lavalink error

**Comment by idMJA** [comment]
> I just tested, I no longer have an error but I still have the problem `Failed to retrieve secret from Spotify.`
> 
> that I no longer had the very first time I used this code
> 
> discord: lucasb25

afaik, config in lavasrc has been renamed from `customAnonymousTokenEndpoint` to `customTokenEndpoint`

https://github.com/topi314/LavaSrc/pull/286#issuecomment-3052232925
